package hello.controleur;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import hello.model.ContenusRepository;
import hello.model.UtilisateurRepository;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/contenus", method = { RequestMethod.POST,
		RequestMethod.GET }) // This means URL's start with /demo (after
								// Application path)
public class ContenusController {
	@Autowired // This means to get the bean called userRepository
				// Which is auto-generated by Spring, we will use it to handle
				// the data
	private ContenusRepository contenusRepository;

	@Autowired
	private UtilisateurRepository utilisateurRepository;


	

}
