package hello.controleur;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

import hello.model.EcoleRepository;
import hello.model.UtilisateurRepository;
import hello.tables.Ecole;
import hello.tables.Utilisateur;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/API/LDAP-synchro", method = { RequestMethod.POST }) // This means URL's start with /demo (after
								// Application path)
public class LDAPSynchroController {
	@Autowired // This means to get the bean called userRepository
				// Which is auto-generated by Spring, we will use it to handle
				// the data
	private UtilisateurRepository userRepository;
	
	@Autowired
	private EcoleRepository ecoleRepository;
	
	@Autowired
	private PasswordEncoder keydEncoder;
	
	@RequestMapping("/ajouter-utilisateur/{schoolKey}")
	
	public @ResponseBody int addUsers( @RequestBody  List<Utilisateur> userList,@PathVariable String schoolKey) {
		Utilisateur first = userList.get(0);
		if (schoolKey!=null && first!=null) {
			Ecole ecole = ecoleRepository.findById(first.getEcole().getId());
			if (keydEncoder.matches(schoolKey, ecole.getKey())) {
				int size = userRepository.save(userList).size();		
			    return size;
			}else {
				return 0;
			}
			
		}else {
			return 0;
		}
		

	}


}
